[OU-FIX] l10n_es: Handle account tags
These data are noupdate=0, so they are tried to be removed by the
standard ORM update. If they have been put in journal items (which is
very likely), on the regular update, they will saying

Error: update or delete on table "account_account_tag" violates foreign key constraint "account_account_tag_account_tax_rep_account_account_tag_id_fkey" on table "account_account_tag_account_tax_repartition_line_rel"
DETAIL:  Key (id)=(NNN) is still referenced from table "account_account_tag_account_tax_repartition_line_rel".

For avoiding this, we delete them safely with the openupgradelib method
that marks them as noupdate=1 in case they can't be removed.