[OU-FIX] account_edi_ubl_cii: Handle EDI formats
These data are noupdate=0, so they are tried to be removed by the
standard ORM update. If they have been put in any invoice (which is
very likely), on the regular update, they will saying

ERROR: update or delete on table "account_edi_format" violates foreign key constraint "account_edi_document_edi_format_id_fkey" on table "account_edi_document"
DETAIL:  Key (id)=(NNN) is still referenced from table "account_edi_document".

For avoiding this, we delete them safely with the openupgradelib method.